spring.application.name=demo


spring.datasource.url=jdbc:mysql://localhost:3306/demo_hackathon
spring.datasource.username=root
spring.datasource.password=Sudheesh@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always